### ISSUE TITLE
Change DateType Storage to ISO 8601

### ISSUE THREAD

**Issue by Aaronontheweb** [fluentcassandra/fluentcassandra#100]
Focus of issue: Change storage mechanism from epoch (long) to ISO 8601 (ToString("u"))

---

We have a number of counter columns which have static CompositeType names, usually something along the lines of `CompositeType<UTF8Type, DateType>` - we use these in wide rows for time-series data for related measures.
## Unit Test to Reproduce Error

One issue I noticed in FluentCassandra is what when I write to a column family using a DateType in any part of a column name (a CounterColumn in this case) the UTC offset specified by the client and the UTC offset written to the server are off - the server always uses the client's UTC offset for both writes and reads.

Here's the unit test I use to reproduce the error:

```
[Test(Description = "Should be able to increment an existing counter")]
public void Should_Increment_Existing_Counter()
{
    var dashboardAppCf = _db.GetColumnFamily("Dashboard_App_Daily");

    var sessionCounterName = CompositeType.Create<UTF8Type, DateType>("Sessions", Date.UtcNow.Date);
    dashboardAppCf.InsertCounterColumn(ProjectId, sessionCounterName, 2);
    dashboardAppCf.InsertCounterColumn(ProjectId, sessionCounterName, Faker.Generators.Numbers.Int(1,10));

    var sessionCounterInDb = dashboardAppCf.GetColumn(ProjectId, sessionCounterName);

    Assert.IsNotNull(sessionCounterInDb);
    Assert.IsTrue(2 <= (int)sessionCounterInDb.ColumnValue);
}
```

When I run it I end up with the following results:
### Error Output

value of column name in FluentCassandra code at runtime: 
{Sessions:1/6/2013 12:00:00 AM +00:00}

value written to server: 
(Sessions, 2013-01-05 16:00:00 UTC)

If I try manually constructing a UTC offset using the `DateTimeOffset` class,  like this:

```
var sessionCounterName = CompositeType.Create<UTF8Type, DateType>("Sessions", new DateTimeOffset(DateTime.UtcNow.Year, DateTime.UtcNow.Month,DateTime.UtcNow.Day, 0,0,0, TimeSpan.Zero));
dashboardAppCf.InsertCounterColumn(ProjectId, sessionCounterName, 2);
```

I still get the same erroneous result 

value of column name in FluentCassandra code at runtime: 
Sessions:1/6/2013 12:00:00 AM +00:00}

value written to server: 
(Sessions, 2013-01-05 16:00:00 UTC)

The issue appears to happen somewhere during the Bytes serialization process, but I wasn't able to pin down where exactly.
## Workaround

I did manage to come up with a workaround in FluentCassandra - if you return the `DateTimeOffset.Date` property of any column name using DateTypes, this will retain the developer-specified UTC offset.

Here's a piece of code I wrote to ensure that we always get just the day in UTC each time we write a piece of data, and it works.

```
public static DateTime UtcDayStart(DateTimeOffset date)
{
    return UtcDayStart(date.Date);
}

public static DateTime UtcDayStart(DateTime date)
{
    return new DateTimeOffset(date.Year, date.Month, date.Day, 0, 0, 0, TimeSpan.Zero).Date;
}
```

**Comment by nberardi** [comment]
This is the line tat serializes it to bytes.

https://github.com/managedfusion/fluentcassandra/blob/master/src/Types/DateTypeConverter.cs#L88

Or since it was a CompositeType it may be here.

https://github.com/managedfusion/fluentcassandra/blob/master/src/Types/CompositeTypeConverter.cs#L78

## 

Nick Berardi
(484) 302-0125
Sent from my tablet.

On Jan 5, 2013, at 7:34 PM, Aaron Stannard notifications@github.com wrote:

We have a number of counter columns which have static CompositeType names,
usually something along the lines of CompositeType<UTF8Type, DateType> - we
use these in wide rows for time-series data for related measures.
Unit Test to Reproduce Error

One issue I noticed in FluentCassandra is what when I write to a column
family using a DateType in any part of a column name (a CounterColumn in
this case) the UTC offset specified by the client and the UTC offset
written to the server are off - the server always uses the client's UTC
offset for both writes and reads.

Here's the unit test I use to reproduce the error:

[Test(Description = "Should be able to increment an existing counter")]
public void Should_Increment_Existing_Counter()
{
    var dashboardAppCf = _db.GetColumnFamily("Dashboard_App_Daily");

```
var sessionCounterName = CompositeType.Create<UTF8Type,
```

DateType>("Sessions", Date.UtcNow.Date);
    dashboardAppCf.InsertCounterColumn(ProjectId, sessionCounterName, 2);
    dashboardAppCf.InsertCounterColumn(ProjectId, sessionCounterName,
Faker.Generators.Numbers.Int(1,10));

```
var sessionCounterInDb = dashboardAppCf.GetColumn(ProjectId,
```

sessionCounterName);

```
Assert.IsNotNull(sessionCounterInDb);
Assert.IsTrue(2 <= (int)sessionCounterInDb.ColumnValue);
```

}

When I run it I end up with the following results:
Error Output

value of column name in FluentCassandra code at runtime:
{Sessions:1/6/2013 12:00:00 AM +00:00}

value written to server:
(Sessions, 2013-01-05 16:00:00 UTC)

If I try manually constructing a UTC offset using the DateTimeOffset class,
like this:

var sessionCounterName = CompositeType.Create<UTF8Type,
DateType>("Sessions", new DateTimeOffset(DateTime.UtcNow.Year,
DateTime.UtcNow.Month,DateTime.UtcNow.Day, 0,0,0, TimeSpan.Zero));
dashboardAppCf.InsertCounterColumn(ProjectId, sessionCounterName, 2);

I still get the same erroneous result

value of column name in FluentCassandra code at runtime:
Sessions:1/6/2013 12:00:00 AM +00:00}

value written to server:
(Sessions, 2013-01-05 16:00:00 UTC)

The issue appears to happen somewhere during the Bytes serialization
process, but I wasn't able to pin down where exactly.
Workaround

I did manage to come up with a workaround in FluentCassandra - if you
return the DateTimeOffset.Date property of any column name using DateTypes,
this will retain the developer-specified UTC offset.

Here's a piece of code I wrote to ensure that we always get just the day in
UTC each time we write a piece of data, and it works.

public static DateTime UtcDayStart(DateTimeOffset date)
{
    return UtcDayStart(date.Date);
}

public static DateTime UtcDayStart(DateTime date)
{
    return new DateTimeOffset(date.Year, date.Month, date.Day, 0, 0,
0, TimeSpan.Zero).Date;
}

 —
Reply to this email directly or view it on
GitHubhttps://github.com/managedfusion/fluentcassandra/issues/100.

**Comment by nberardi** [comment]
So I broke out the code to make it more digestible.

``` csharp
var sessionCounterName = CompositeType.Create<UTF8Type, DateType>("Sessions", new DateTimeOffset(DateTime.UtcNow.Year, DateTime.UtcNow.Month, DateTime.UtcNow.Day, 0, 0, 0, TimeSpan.Zero));
var date = sessionCounterName.Item2;
var l = date.GetValue<long>();

l = 1357430400000
```

I then plugged `l` into this website http://www.epochconverter.com/ to see what the resulting epoch value was, and it was right on the money.

```
Sun, 06 Jan 2013 00:00:00 GMT
```

Are you sure that whatever algorithm you are using to see the date written to the server is correct?  Because it seems like it is taking the server value, applying your local offset and then just slapping UTC on the end.  I could be wrong, but I would look at the raw value written to the server and base the problem off that.  And the raw value is a `long`.  Let me know what you find, I am interested in tracking down where the issue is.

**Comment by Aaronontheweb** [comment]
It could very well be that the server is applying it's own UTC offset, although I find that troubling in the second case where I explicitly set a UTC offset (of 0, in this case) using DateTimeOffset. I should note that I'm able to retrieve the value just fine from the client - my worry is that without being able to standardize to UTC I may end up in a situation where I'm misplacing data due to whatever timezone setting the client or server uses being different.

I've been using DataStax OpsCenter to view the value, and just in case that was messing things up I used the CLI and retrieved these values - one from the error case and one from my workaround:

Error Case:
Sessions:2013-01-05 16:00:00-0800

Workaround:
Sessions:2013-01-06 00:00:00-0800

It looks like my PST (GMT-8) offset keeps getting slapped onto the end even though I've explicitly set it to zero in my client, although at least the Date is accurate for the second example. 

Does Cassandra itself append the server UTC offset on the end dates sent by the client? Otherwise, this seems like the client-supplied UTC offset is lost in translation.

**Comment by nberardi** [comment]
Can you try from the CQLSH and see what is returned?

## 

Nick Berardi
(484) 302-0125
Sent on the go from my phone.

On Jan 5, 2013, at 10:17 PM, Aaron Stannard notifications@github.com
wrote:

It could very well be that the server is applying it's own UTC offset,
although I find that troubling in the second case where I explicitly set a
UTC offset (of 0, in this case) using DateTimeOffset. I should note that
I'm able to retrieve the value just fine from the client - my worry is that
without being able to standardize to UTC I may end up in a situation where
I'm misplacing data due to whatever timezone setting the client or server
uses being different.

I've been using DataStax OpsCenter to view the value, and just in case that
was messing things up I used the CLI and retrieved these values - one from
the error case and one from my workaround:

Error Case:
Sessions:2013-01-05 16:00:00-0800

Workaround:
Sessions:2013-01-06 00:00:00-0800

It looks like my PST (GMT-8) offset keeps getting slapped onto the end even
though I've explicitly set it to zero in my client, although at least the
Date is accurate for the second example.

Does Cassandra itself append the server UTC offset on the end dates sent by
the client? Otherwise, this seems like the client-supplied UTC offset is
lost in translation.

—
Reply to this email directly or view it on
GitHubhttps://github.com/managedfusion/fluentcassandra/issues/100#issuecomment-11923744.

**Comment by Aaronontheweb** [comment]
```
cqlsh:markedup_analytics> SELECT * FROM Dashboard_App_Daily;
 KEY,Projects-15883 | '\x00\x08Sessions\x00\x00\x08\x00\x00\x01<\r($\x00\x00',10

 KEY,Projects-10700 | '\x00\x08Sessions\x00\x00\x08\x00\x00\x01<\x0e\xdf\x98\x00
\x00',9

Failed to decode column name '\x00\x08Sessions\x00\x00\x08\x00\x00\x01<\r($\x00\
x00' as 'org.apache.cassandra.db.marshal.CompositeType': global name 'self' is n
ot defined
Failed to decode column name '\x00\x08Sessions\x00\x00\x08\x00\x00\x01<\x0e\xdf\
x98\x00\x00' as 'org.apache.cassandra.db.marshal.CompositeType': global name 'se
lf' is not defined
```

I don't think the latest version of DataStax Community edition ships with CQL3 yet, :(

**Comment by Aaronontheweb** [comment]
I have another idea - let me try that out

**Comment by Aaronontheweb** [comment]
Doh! When I changed the calling code to grab the entire counter row instead of just a single column, as below:

```
var sessionCounterName = CompositeType.Create<UTF8Type, DateType>("Sessions", new DateTimeOffset(DateTime.UtcNow.Year, DateTime.UtcNow.Month,DateTime.UtcNow.Day, 0,0,0, TimeSpan.Zero)); 
dashboardAppCf.InsertCounterColumn(ProjectId, sessionCounterName, 2);
dashboardAppCf.InsertCounterColumn(ProjectId, sessionCounterName, Faker.Generators.Numbers.Int(1,10));

var sessionCounterInDb = dashboardAppCf.Get(ProjectId).FirstOrDefault();
```

I ran into a deserialization error from FluentCassandra - I'm going to investigate.

**Comment by eplowe** [comment]
http://cassandra.apache.org/doc/cql3/CQL.html#usingdates

It seems that if you just send a long for the timestamp Cassandra will use
the time zone configured on the server. Even though this is a cql 3 ref. If
my memory serves me it should be applicable for Cassandra in general .

**Comment by Aaronontheweb** [comment]
@eplowe @nberardi got it - so two quick questions for you:
1. Is there a way to specify a timezone for Cassandra in the .yaml file?
2. Is there an alternative way to send the DateTime via Thrift that doesn't require converting it to a long?

**Comment by nberardi** [comment]
That is not how I read it. What they said was for ISO 8601 if you don't
include the time zone one will be added from the server.

Longs stay as longs. Which seems to be inline with the fact the same value
is retrieved that is inserted.

## 

Nick Berardi
(484) 302-0125
Sent on the go from my phone.

On Jan 5, 2013, at 10:25 PM, Eric Plowe notifications@github.com wrote:

http://cassandra.apache.org/doc/cql3/CQL.html#usingdates

It seems that if you just send a long for the timestamp Cassandra will use
the time zone configured on the server. Even though this is a cql 3 ref. If
my memory serves me it should be applicable for Cassandra in general .
On Jan 5, 2013 10:21 PM, "Aaron Stannard" notifications@github.com wrote:

> cqlsh:markedup_analytics> SELECT \* FROM Dashboard_App_Daily;
> KEY,Projects-15883 |
> '\x00\x08Sessions\x00\x00\x08\x00\x00\x01<\r($\x00\x00',10
> 
> KEY,Projects-10700 |
> '\x00\x08Sessions\x00\x00\x08\x00\x00\x01<\x0e\xdf\x98\x00
> \x00',9
> 
> Failed to decode column name
> '\x00\x08Sessions\x00\x00\x08\x00\x00\x01<\r($\x00\
> x00' as 'org.apache.cassandra.db.marshal.CompositeType': global name
> 'self' is n
> ot defined
> Failed to decode column name
> '\x00\x08Sessions\x00\x00\x08\x00\x00\x01<\x0e\xdf\
> x98\x00\x00' as 'org.apache.cassandra.db.marshal.CompositeType': global
> name 'se
> lf' is not defined
> 
> I don't think the latest version of DataStax Community edition ships with
> CQL3 yet, :(
> 
> —
> Reply to this email directly or view it on GitHub<
> https://github.com/managedfusion/fluentcassandra/issues/100#issuecomment-11923781>.

—
Reply to this email directly or view it on
GitHubhttps://github.com/managedfusion/fluentcassandra/issues/100#issuecomment-11923809.

**Comment by nberardi** [comment]
Not that I am aware of on both accounts.

By the way the difference you are seeing with date times is because the
DateTime object doesn't specify a time zone. So I had to choose UTC or
Local for when spitting it out. And I choose Local because that is the most
common use of DateTime.

Switch to DateTimeOffset if you want it to work. While the time zone is
reset to UTC when retrieved it is the exact value you put in.

## 

Nick Berardi
(484) 302-0125
Sent on the go from my phone.

On Jan 5, 2013, at 10:28 PM, Aaron Stannard notifications@github.com
wrote:

@eplowe https://github.com/eplowe @nberardi
https://github.com/nberardigot it - so two quick questions for you:
1. Is there a way to specify a timezone for Cassandra in the .yaml file?
2. Is there an alternative way to send the DateTime via Thrift that
   doesn't require converting it to a long?
   
   —
   Reply to this email directly or view it on
   GitHubhttps://github.com/managedfusion/fluentcassandra/issues/100#issuecomment-11923841.

**Comment by eplowe** [comment]
Sorry for the confusion I was typing on my phone -- yes, you're right.

**Comment by Aaronontheweb** [comment]
I fixed a bug in FluentCassandra that prevented me from being able to do a multiget slice of counter columns (pull request coming shortly), and here's what I got back for the column names:

With DateTimeOffset specified, prior to Write:
{Sessions:2013-01-06 00:00:00Z = 8} 

Value on Server:
(counter=Sessions:2013-01-05 16:00:00-0800, value=8)

Read back onto Client from the server
{Sessions:2013-01-06 00:00:00Z = 8} 

Ignore the integer values - just random increments of the counters in my unit test.

@nberardi even though I'm using DateTimeOffset, my offset is still being lost in translation onto the server. What scares me about this is that we're going to be connecting to Cassandra from multiple physical locations and multiple languages (Hadoop + Java) - we standardize our dates for column names on UTC to make this easy to manage.

Is there a way we can change the serialization behavior so it'll preserve whatever the developer set for DateTimeOffset?

**Comment by nberardi** [comment]
The problem with epoch is that there are no time zones. So no matter what
you put in only UTC can be pulled out.

Plus you only get millisecond resolution. So if you need more than that you
are out of luck.

The alternative is to use Long and put ticks into the database.

## 

Nick Berardi
(484) 302-0125
Sent on the go from my phone.

On Jan 5, 2013, at 11:07 PM, Aaron Stannard notifications@github.com
wrote:

I fixed a bug in FluentCassandra that prevented me from being able to do a
multiget slice of counter columns (pull request coming shortly), and here's
what I got back for the column names:

With DateTimeOffset specified, prior to Write:
{Sessions:2013-01-06 00:00:00Z = 8}

Value on Server:
(counter=Sessions:2013-01-05 16:00:00-0800, value=8)

Read back onto Client from the server
{Sessions:2013-01-06 00:00:00Z = 8}

Ignore the integer values - just random increments of the counters in my
unit test.

@nberardi https://github.com/nberardi even though I'm using
DateTimeOffset, my offset is still being lost in translation onto the
server. What scares me about this is that we're going to be connecting to
Cassandra from multiple physical locations and multiple languages (Hadoop +
Java) - we standardize our dates for column names on UTC to make this easy
to manage.

Is there a way we can change the serialization behavior so it'll preserve
whatever the developer set for DateTimeOffset?

—
Reply to this email directly or view it on
GitHubhttps://github.com/managedfusion/fluentcassandra/issues/100#issuecomment-11924138.

**Comment by nberardi** [comment]
It looks like Cassandra may have changed the DateType.

http://grepcode.com/file/repo1.maven.org/maven2/org.apache.cassandra/cassandra-all/1.2.0-beta1/org/apache/cassandra/db/marshal/DateType.java

It looks like it supports ISO 8601. Which might be slightly slower reading
and consuming over a long. But would hopefully solve the time zone issue.

If you want to tackle this be my guess in a different pull request.

## 

Nick Berardi
(484) 302-0125
Sent on the go from my phone.

On Jan 5, 2013, at 11:07 PM, Aaron Stannard notifications@github.com
wrote:

I fixed a bug in FluentCassandra that prevented me from being able to do a
multiget slice of counter columns (pull request coming shortly), and here's
what I got back for the column names:

With DateTimeOffset specified, prior to Write:
{Sessions:2013-01-06 00:00:00Z = 8}

Value on Server:
(counter=Sessions:2013-01-05 16:00:00-0800, value=8)

Read back onto Client from the server
{Sessions:2013-01-06 00:00:00Z = 8}

Ignore the integer values - just random increments of the counters in my
unit test.

@nberardi https://github.com/nberardi even though I'm using
DateTimeOffset, my offset is still being lost in translation onto the
server. What scares me about this is that we're going to be connecting to
Cassandra from multiple physical locations and multiple languages (Hadoop +
Java) - we standardize our dates for column names on UTC to make this easy
to manage.

Is there a way we can change the serialization behavior so it'll preserve
whatever the developer set for DateTimeOffset?

—
Reply to this email directly or view it on
GitHubhttps://github.com/managedfusion/fluentcassandra/issues/100#issuecomment-11924138.

**Comment by Aaronontheweb** [comment]
@nberardi thanks - I'll look into it. For now I decided to take your advice and use a long - probably a better practice anyway.

**Comment by nberardi** [comment]
Since ISO 8601 is probably the recommended way to go, lets make the focus of this issue changing the storage mechanism from long to ISO 8601.

**Comment by nberardi** [comment]
I was wrong, they still require milliseconds to be sent in through the RPC interface.  The other formats only work though CQL.

The composer that takes the ByteBuffer is the key indicator in this.

http://grepcode.com/file/repo1.maven.org/maven2/org.apache.cassandra/cassandra-all/1.2.0-beta1/org/apache/cassandra/db/marshal/DateType.java#43

This is just going to have to be one of those issues, I am open to solutions, but it doesn't appear we have many options.
