### ISSUE TITLE
CompositeType wont serialize properly for col name

### ISSUE THREAD

**Issue by gillotte** [fluentcassandra/fluentcassandra#120]
Hi Nick, consider the following

```
CompositeType colname = new CompositeType(new CassandraType[] { CassandraType.AsciiType, CassandraType.AsciiType });            
        AsciiType k1 = new AsciiType();
        k1.SetValue("key2");
        AsciiType k2 = new AsciiType();
        k2.SetValue("key3");
        colname.SetValue(new CassandraObject[] { k1, k2 });

        var record = cf.CreateRecord(key);
        record[colname] = colValue;
```

this fails essentially because this line fails

```
        var val1 = colname.GetValue(CassandraType.GetCassandraType(typeof(byte[])));
```

A proposed fix:

Edit CassandraObject's Get Value to include bytetype clause.

```
public CassandraObject GetValue(CassandraType type)
    {
        if (type.FluentType == GetType())
            return this;

        if (GetType() == typeof(BytesType))
            return GetCassandraObjectFromDatabaseByteArray((byte[])GetValue(), type);

        //NEW CODE
        if (type == CassandraType.BytesType)
            return ToBigEndian();

        return GetCassandraObjectFromObject(GetValue(), type);
    }
```

thoughts?

**Comment by nberardi** [comment]
Can you send a pull request with a test showing the failure.

## 

Nick Berardi
(484) 302-0125
Sent on the go from my phone.

On Mar 18, 2013, at 6:12 AM, gillotte notifications@github.com wrote:

Hi Nick, consider the following

CompositeType colname = new CompositeType(new CassandraType[] {
CassandraType.AsciiType, CassandraType.AsciiType });
        AsciiType k1 = new AsciiType();
        k1.SetValue("key2");
        AsciiType k2 = new AsciiType();
        k2.SetValue("key3");
        colname.SetValue(new CassandraObject[] { k1, k2 });

```
    var record = cf.CreateRecord(key);
    record[colname] = colValue;
```

this fails essentially because this line fails

```
    var val1 =
```

colname.GetValue(CassandraType.GetCassandraType(typeof(byte[])));

A proposed fix:

Edit CassandraObject's Get Value to include bytetype clause.

public CassandraObject GetValue(CassandraType type)
    {
        if (type.FluentType == GetType())
            return this;

```
    if (GetType() == typeof(BytesType))
        return
```

GetCassandraObjectFromDatabaseByteArray((byte[])GetValue(), type);

```
    //NEW CODE
    if (type == CassandraType.BytesType)
        return ToBigEndian();

    return GetCassandraObjectFromObject(GetValue(), type);
}
```

thoughts?

—
Reply to this email directly or view it on
GitHubhttps://github.com/managedfusion/fluentcassandra/issues/120
.
