### ISSUE TITLE
not clear if record.TrySetColumn() is a valid way to set a named column

### ISSUE THREAD

**Issue by razzmatazz** [fluentcassandra/fluentcassandra#13]
Take this code:

```
            IEnumerable<string> listOfColNames = new [] { "abc", "cba", "xxx" };

            var record = family.CreateRecord(123);

            foreach(var col in listOfColNames)
                record.TrySetColumn(col, "aa");
```

Is it a correct way to set named columns this way? The "Try" prefix on the method doesn't encourage trust that this is a legal API to use for this purpose.

**Comment by nberardi** [comment]
These methods are designed to be used to support the dynamic keyword.  There isn't really anyway to delete them or make them private given DynamicObject's exposed methods.  Technically there is nothing wrong with what you have done, but it should be discouraged.  Which is why I have added the:

```
[EditorBrowsable(EditorBrowsableState.Never)]
```

To the dynamic support methods.
