### ISSUE TITLE
Check the ColumnName is existing

### ISSUE THREAD

**Issue by robinsu** [fluentcassandra/fluentcassandra#2]
In 2010/06/14 update, the dynamic properties will return default cast value instead of throw a runtime exception. Basically, it is great approach and avoid throw exception.
But, In some scenario, it will cause confuse between default value and null value. Does any method to check ColumnName is existing or any suggestions ? 

Thanks a lot,
- ROBIN SU

**Comment by managedfusion** [comment]
Good question.  I hid away the NullType that is being returned, but maybe I should make it public so that you can check the type being returned.  Do you have a way you would like to work with a non-existant column?

**Comment by robinsu** [comment]
there are two options which our wish. 
1. provide one method function to check the column is existing or not.
2. support using .Net generic Nullable<> Type.

we are very appreciate to your great help and valuable support.
Thank you very much,

**Comment by nberardi** [comment]
Sorry this has taken so long, but I have finally found some time to add the feature you requested.

http://github.com/managedfusion/fluentcassandra/commit/3cf99745f37951d4003486f2c07d78a252adf26e

Now you will be able to use the method

if (ColumnExists("ColumnName"))

And you can now cast to Nullable types if and when supported by the underlying Cassandra type.

Let me know if this solves you issue.

**Comment by robinsu** [comment]
Thank you so much !!

**Comment by timoaho** [comment]
I have the same problem as the original poster.

The method public virtual bool FluentRecord.FluentCassandra.ColumnExists(string name) seems to have been removed from FluentRecord.cs in the following commit:
https://github.com/managedfusion/fluentcassandra/commit/1b28998917894da17fb0911ff69d313bc6b6004b#src/FluentRecord.cs

I could not find the functionality anywhere else. Do I miss something?

**Comment by nberardi** [comment]
The method had a number of problems. Because column names can be any of the types not just string. And it didn't work so well for dynamic types. So dynamic properties will just return null if it isn't present. 

However I may have overlooked the POCO users of this object.  If you are interested I would be interested in taking in a pull request to support this for POCO uses. 

Here you can sort of see how I am comparing column names. 

https://github.com/managedfusion/fluentcassandra/blob/master/src/FluentColumnFamily.cs#L170

However instead of object you would want to use CassandraObject.
